# Copyright (c) 2026 dev&din. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.

import("//brave/components/common/typescript.gni")
import("//brave/resources/brave_grit.gni")
import("//mojo/public/tools/bindings/mojom.gni")
import("//tools/grit/repack.gni")

transpile_web_ui("basarunaa_panel_ui") {
  output_module = false
  entry_points = [ [
        "basarunaa_panel",
        rebase_path("basarunaa_panel.ts"),
      ] ]
  resource_name = "basarunaa_panel"

  imports_from = [ "//brave/components/basarunaa/resources/panel/" ]

  deps = [
    "//brave/components/basarunaa/common/mojom:mojom_js",
    "//brave/components/basarunaa/common/mojom:preprocess_mojo",
  ]
}

pack_web_resources("basarunaa_panel_generated") {
  resource_name = "basarunaa_panel"
  output_dir = "$root_gen_dir/brave/components/basarunaa/resources/panel"
  deps = [ ":basarunaa_panel_ui" ]
}

repack("resources") {
  sources = [ "$root_gen_dir/brave/components/basarunaa/resources/panel/basarunaa_panel_generated.pak" ]

  deps = [ ":basarunaa_panel_generated" ]

  output =
      "$root_gen_dir/brave/components/basarunaa/basarunaa_panel_resources.pak"
}
