# Copyright (c) 2026 The Browther Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.

source_set("browther_analytics") {
  sources = [
    "analytics_config.h",
    "browther_analytics_service.cc",
    "browther_analytics_service.h",
    "distinct_id_provider.cc",
    "distinct_id_provider.h",
    "posthog_client.cc",
    "posthog_client.h",
    "pref_names.h",
  ]

  deps = [
    "//base",
    "//brave/components/p3a",
    "//components/metrics",
    "//components/prefs",
    "//net/traffic_annotation",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//url",
  ]
}
