// Copyright (c) 2024 The Brave Authors. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

import Foundation
import UIKit

struct AltIcon: Identifiable {
  var assetName: String
  var displayName: String

  var id: String {
    assetName
  }

  // Browther: shield variants. Assets are generated by
  // private/assets/deploy-assets.sh (§ 13c2) from logo/browther/icon/alternatives/,
  // which also rewrites ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES and warns
  // when this list and the deployed catalogs drift apart.
  static let galaxy = AltIcon(assetName: "galaxy", displayName: "Galaxy")
  static let it = AltIcon(assetName: "it", displayName: "Tech")
  static let metal = AltIcon(assetName: "metal", displayName: "Metal")
  static let neon = AltIcon(assetName: "neon", displayName: "Neon")
  static let pink = AltIcon(assetName: "pink", displayName: "Pink")
  static let plant = AltIcon(assetName: "plant", displayName: "Plant")
  static let queen = AltIcon(assetName: "queen", displayName: "Queen")
  static let water = AltIcon(assetName: "water", displayName: "Water")

  static let allBrowtherIcons: [AltIcon] = [
    .galaxy,
    .it,
    .metal,
    .neon,
    .pink,
    .plant,
    .queen,
    .water,
  ]
}

class AltIconsModel: ObservableObject {
  @Published private(set) var selectedAltAppIcon: String?

  init() {
    self.selectedAltAppIcon = UIApplication.shared.alternateIconName
  }

  func setAlternateAppIcon(_ icon: AltIcon?, completion: ((Error?) -> Void)?) {
    if icon?.assetName == selectedAltAppIcon {
      // Nothing to do
      completion?(nil)
      return
    }
    UIApplication.shared.setAlternateIconName(icon?.assetName) { error in
      if error == nil {
        self.selectedAltAppIcon = icon?.assetName
      }
      completion?(error)
    }
  }
}
