# Copyright (c) 2026 dev&din. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

static_library("basarunaa") {
  sources = [
    "basarunaa_image_analyzer.cc",
    "basarunaa_image_analyzer.h",
    "basarunaa_service_factory.cc",
    "basarunaa_service_factory.h",
  ]

  deps = [
    "//base",
    "//brave/components/basarunaa/common/mojom",
    "//brave/components/basarunaa/core",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//content/public/browser",
    "//mojo/public/cpp/base",
    "//mojo/public/cpp/bindings",
  ]
}
