# Copyright (c) 2026 The Browther Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# you can obtain one at https://mozilla.org/MPL/2.0/.

import("//build/config/android/rules.gni")

assert(is_android)

source_set("browther_analytics") {
  sources = [ "browther_analytics_android.cc" ]

  deps = [
    "//base",
    "//brave/build/android:jni_headers",
    "//brave/components/browther_analytics",
    "//brave/components/p3a",
    "//chrome/browser:browser_process",
    "//components/metrics",
    "//components/prefs",
  ]
}
